### ISSUE TITLE
fixtures.json file is generated even without the command line argument

### ISSUE THREAD

**Issue by ToddBradley** [marcosanchotene/pytest-json-fixtures#2]
Using the latest version of Python 3.11 and `pytest-json-fixtures` 0.1.2, running tests generates a `fixtures.json` file even if you don't specify the `--json-fixtures` command line argument. The plugin code is triggered just by being there.

I don't know much about custom Pytest hooks, but I suspect this is because of the way the hook is registered on line 23 of `pytest_json_fixtures.py`.

```python
@pytest.hookimpl(tryfirst=True, hookwrapper=True)
```

The hook code is always called. Maybe the original intent was to just bypass most of the `pytest_collection_modifyitems` function if the command line argument wasn't provided. That's my guess for why the `if filename` check exists on line 26. However, `filename` is *always* set. Even if the user doesn't specify one, it's set to the default string "fixtures.json" because of line 18.

**Comment by marcosanchotene** [comment]
Closed with https://github.com/marcosanchotene/pytest-json-fixtures/pull/5
