### ISSUE TITLE
Tests should not be executed if --json-fixtures is used

### ISSUE THREAD

**Issue by ToddBradley** [marcosanchotene/pytest-json-fixtures#3]
I don't know if this is a bug or an enhancement request. You decide.

If you use the `--json-fixtures` command line argument to Pytest, Pytest runs tests in addition to printing out the fixture information. This is different than how the build-in `--fixtures` command line argument works. If you use `--fixtures` then Pytest doesn't run your tests; it just prints out the fixture information.

I expected `--json-fixtures` to work the same way as `--fixtures`. As currently implemented, it means it's impossible to *only* generate the list of fixtures without running tests. For long running tests, this is overkill. On my test project, running the tests takes a couple minutes, but generating the fixtures file only takes a couple seconds.

**Comment by marcosanchotene** [comment]
Closed with https://github.com/marcosanchotene/pytest-json-fixtures/pull/5
