### ISSUE TITLE
JSON fixtures should be sent to stdout, not a file

### ISSUE THREAD

**Issue by ToddBradley** [marcosanchotene/pytest-json-fixtures#4]
This one's definitely an enhancement, not a bug.

I think that when I use `--json-fixtures` the output should be sent to the standard output, not to a file. This mirrors how `--fixtures` works. Besides, we all know how to redirect the JSON to a file if needed.

The tough part of implementing this will be suppressing non-JSON output from Pytest when using `--json-fixtures` so that you don't end up with a mish-mash of JSON and log output.

**Comment by marcosanchotene** [comment]
Closed with https://github.com/marcosanchotene/pytest-json-fixtures/pull/5
